"""
Guardrails — Output Filter
============================
Sanitises LLM responses before they are sent to the user.

Three layers:
1. **Replace** over-promising language with safe alternatives.
2. **Append disclaimer** when sensitive financial / legal claims are detected.
3. **Redact** hallucinated / fabricated offer terms.
"""

import re

from guardrails.keywords import (
    BANNED_OUTPUT_REPLACEMENTS,
    SENSITIVE_OUTPUT_KEYWORDS,
    HALLUCINATED_KEYWORDS,
    DISCLAIMER_TEXT,
)
from services.logger import get_logger

logger = get_logger(__name__)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def clean_output(response: str) -> str:
    """
    Run the LLM response through all output guardrails.

    Processing order:
    1. Replace banned over-promising phrases.
    2. Redact hallucinated / fabricated offer terms.
    3. Append disclaimer if sensitive financial / legal claims are found.

    Args:
        response: Raw text generated by the LLM.

    Returns:
        Sanitised response string safe to return to the user.
    """
    if not response:
        return response

    cleaned = response
    response_lower = cleaned.lower()

    # ------------------------------------------------------------------
    # 1. Replace over-promising language
    # ------------------------------------------------------------------
    for banned_phrase, safe_phrase in BANNED_OUTPUT_REPLACEMENTS.items():
        if banned_phrase in response_lower:
            logger.info("Output REPLACED | '%s' → '%s'", banned_phrase, safe_phrase)
            cleaned = re.sub(
                re.escape(banned_phrase), safe_phrase, cleaned, flags=re.IGNORECASE
            )
            response_lower = cleaned.lower()  # refresh for next checks

    # ------------------------------------------------------------------
    # 2. Redact hallucinated / fabricated offers
    # ------------------------------------------------------------------
    for fake_term in HALLUCINATED_KEYWORDS:
        if fake_term in response_lower:
            logger.info("Output REDACTED | hallucinated term='%s'", fake_term)
            cleaned = re.sub(
                re.escape(fake_term),
                "[information not verified]",
                cleaned,
                flags=re.IGNORECASE,
            )
            response_lower = cleaned.lower()

    # ------------------------------------------------------------------
    # 3. Append disclaimer for sensitive claims
    # ------------------------------------------------------------------
    needs_disclaimer = any(kw in response_lower for kw in SENSITIVE_OUTPUT_KEYWORDS)
    if needs_disclaimer:
        logger.info("Output — disclaimer appended (sensitive claim detected)")
        if DISCLAIMER_TEXT.strip() not in cleaned:
            cleaned += DISCLAIMER_TEXT

    return cleaned
